
--[[
 * A simple token class. These are generated by Lexer and consumed by Parser.
--]]
---@class Token
---@field getType function
---@field getText function

---@param type TokenType
---@param text string
---@return Token
return function(type, text)
  local mType = type
  local mText = text

  return {
    ---@return TokenType
    getType = function()
      return mType
    end,

    ---@return string
    getText = function()
      return mText
    end,

    -- -- @Override
    -- ---@return string
    -- toString = function()
    --   return mText
    -- end,
  }
end
